# Generated by Django 3.1.4 on 2020-12-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_auto_20201227_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_set',
            new_name='tag_set',
        ),
    ]
